// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwyjJgIOgY7LQjjjP2VIrQA-Zg3GQdPNA',
    appId: '1:855015056699:android:46041f5a5b09d9acd5831e',
    messagingSenderId: '855015056699',
    projectId: 'supercycle-b07f1',
    storageBucket: 'supercycle-b07f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG_5oBp_J6f-U18miyfMHaeJazgVGSHH0',
    appId: '1:855015056699:ios:44aea07da6acba97d5831e',
    messagingSenderId: '855015056699',
    projectId: 'supercycle-b07f1',
    storageBucket: 'supercycle-b07f1.firebasestorage.app',
    iosBundleId: 'com.example.supercycleApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5V63HzMuZSizeKPnpLbWUOnSkNhCWsfA',
    appId: '1:855015056699:web:250f27484e8cae98d5831e',
    messagingSenderId: '855015056699',
    projectId: 'supercycle-b07f1',
    authDomain: 'supercycle-b07f1.firebaseapp.com',
    storageBucket: 'supercycle-b07f1.firebasestorage.app',
  );
}
